custom:
  swagger:
    enable: true #是否启用swagger文档
  log:
    path: D:/logback/${spring.application.name}/${spring.profiles.active}
  token: 
      userClaim: userInfo
      survivalTime: 7200000
      secret: EC86@34$123c
    
spring:
  application:
    name: szedu
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/szedu?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.31.128:22122

    
server:
  port: 8080
